# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(blank=True, upload_to=users.models.upload_location, verbose_name='CV'),
        ),
    ]
