# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='career_describ',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
