# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='https://unsplash.it/1100', upload_to=events.models.upload_posters_location, verbose_name='Poster'),
        ),
    ]
