# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170828_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position_latt',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='position_long',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
