# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 17:51
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170901_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='position_latt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='position_long',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
    ]
