# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 18:00
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170901_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
