# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 18:04
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
    ]
