# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 10:00
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('sources', models.TextField(null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b'')),
                ('language', models.CharField(choices=[('FRENCH', 'Fr'), ('ARABE', 'Ar'), ('ENGLISH', 'En')], default='ARABE', max_length=60)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-posted', '-updated'],
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=articles.models.upload_location, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
