# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170825_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
