# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 20:44
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170829_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('FRENCH', 'fr'), ('ARABE', 'ar'), ('ENGLISH', 'en')], default='ARABE', max_length=60),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=articles.models.upload_location, verbose_name='Image'),
        ),
    ]
