# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20170901_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last update'),
        ),
    ]
