# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20170902_2016'),
        ('articles', '0010_auto_20170902_2035'),
    ]

    operations = [
    ]
