# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 18:29
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_merge_20170902_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, help_text='Document to join in article for download', null=True, upload_to=articles.models.upload_locationpdf, verbose_name='Document'),
        ),
    ]
