# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 01:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
import data.models
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEF_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_name', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(default='foundation-logo.png', upload_to=data.models.upload_locationlogo)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('privacy', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Privacy')),
                ('policy', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Policy')),
                ('foundation_gmail', models.CharField(max_length=100, verbose_name='Email')),
                ('foundation_phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('foundation_address', models.CharField(max_length=100, verbose_name='Address')),
                ('foundation_location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
            ],
            options={
                'verbose_name': 'Foundation_data',
                'verbose_name_plural': 'Foundation_datas',
            },
        ),
        migrations.CreateModel(
            name='Slogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=data.models.upload_location)),
                ('alt_text', models.CharField(help_text='Descripe your image, this field is important to search engines and for web accessibility', max_length=100, verbose_name='Image description')),
                ('slogo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.SEF_data')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
