# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 02:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sef_data',
            name='foundation_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sef_data',
            name='logo',
            field=models.ImageField(upload_to=data.models.upload_locationlogo),
        ),
        migrations.AlterField(
            model_name='sef_data',
            name='policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Policy'),
        ),
        migrations.AlterField(
            model_name='sef_data',
            name='privacy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Privacy'),
        ),
    ]
